name: CI

on:
  push:
    branches: ['production']
  pull_request:
    branches: ['production']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scripts
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd analyst-nest
            echo "Running git pull"
            sudo git pull
            echo "Running npm ci"
            sudo npm ci
            echo "Running npm run build"
            sudo npm run build
            echo "Restarting pm2"
            sudo pm2 restart analyst
          timeout: 5m
